### ISSUE TITLE
Parsing of /etc/resolv.conf fails because of incorrect inferred type

### ISSUE THREAD

**Issue by drmikehenry** [SergejJurecko/mio_httpc#19]
The parsing of `/etc/resolv.conf` to determine a nameserver isn't working; because parsing fails, this line is never executed:
https://github.com/SergejJurecko/mio_httpc/blob/1804900b00ef20c1dd8086c52960e292c3325540/src/resolve/mod.rs#L280

The file `/etc/resolv.conf` contains lines like the below to configure a nameserver:
```
nameserver 127.0.0.53
```

The IP address is currently being parsed into a `SocketAddr` struct (inferred to be that type due to the linked line of source above).  This parsing always fails due to the lack of `:port` after the IP address.

Parsing operates correctly if the inferred type is `IpAddress` and a fixed port number of `53` is provided, as in the replacement line below:
```rust
srvs.push(SocketAddr::new(adr, 53));
```

**Comment by SergejJurecko** [comment]
thank you
