### ISSUE TITLE
Times out fetching http://google.com

### ISSUE THREAD

**Issue by Shnatsel** [SergejJurecko/mio_httpc#25]
Fetching some URLs, notably `http://google.com`, times out. Other clients such as curl, ureq, reqwest, etc work fine.

Self-contained for reproducing the issue can be found here:
https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/34ecea4ceacda1ac6134c4037c1bc9227254c87b/mio_httpc-smoke-test/src/main.rs

**Comment by SergejJurecko** [comment]
Thanks fixed in 0.9.3
