### ISSUE TITLE
Switch from libflate to miniz_oxide

### ISSUE THREAD

**Issue by Shnatsel** [SergejJurecko/mio_httpc#26]
`flate2` crate is significantly slower than [`miniz_oxide`](https://crates.io/crates/miniz_oxide) crate. Most HTTP clients use `miniz_oxide`. `mio_httpc` already depends on `miniz_oxide` transitively via `failure` crate; it would be nice to switch to it for HTTP stream decoding too.

The only thing missing from `miniz_oxide` is gzip header decoding, but it is provided by the [`flate2`](https://crates.io/crates/flate2) crate that wraps it.

**Comment by SergejJurecko** [comment]
While testing if libflate is the issue, I've switched to flate2 to see if it also returns error on some websites and it does. Also tried with gunzip command and it failed. So I will just keep it on flate2 I guess.

**Comment by Shnatsel** [comment]
Performance is the primary reason to switch to `miniz_oxide` - `libflate` is significantly slower in decoding, and only does some very light compression in encoding.
