### ISSUE TITLE
Panic on index out of bounds in /src/types.rs:285:50

### ISSUE THREAD

**Issue by Shnatsel** [SergejJurecko/mio_httpc#27]
On some websites, e.g. http://yakitoriya.ru , mio_httpc panics with the following error: 

> thread 'main' panicked at 'index out of bounds: the len is 5 but the index is 5', /home/shnatsel/.cargo/registry/src/github.com-1ecc6299db9ec823/mio_httpc-0.9.3/src/types.rs:285:50

The error message can also point to index 6 rather than 5.

curl and Firefox work fine.

There's at least 43 such websites in the top million (I'm using [Tranco list generated on the 3rd of February](https://tranco-list.eu/list/3G6L)).

Archive with all occurrences (although I didn't run the test on the entire million): [mio_httpc-oob-panic.tar.gz](https://github.com/SergejJurecko/mio_httpc/files/5984578/mio_httpc-oob-panic.tar.gz)

Code used for testing: https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/f206362f2e81521bbefb84007cdd25242f6db590/mio_httpc-smoke-test/src/main.rs

**Comment by SergejJurecko** [comment]
Thank  you fixed in 0.9.4
