### ISSUE TITLE
Panic on unwrapping in /src/resolve/mod.rs:18:37 on some websites

### ISSUE THREAD

**Issue by Shnatsel** [SergejJurecko/mio_httpc#28]
On some websites, e.g. http://humaxdigital.com, mio_httpc panics with the following error: 

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidQueryType { code: 3176 }', /home/shnatsel/.cargo/registry/src/github.com-1ecc6299db9ec823/mio_httpc-0.9.3/src/resolve/mod.rs:18:37

Checking the website with Firefox, it appears that it redirects to an invalid domain name.

There's at least 7 such websites in the top million (I'm using [Tranco list generated on the 3rd of February](https://tranco-list.eu/list/3G6L)).

Archive with all occurrences (although I didn't run the test on the entire million): [mio_httpc-unwrap-panic.tar.gz](https://github.com/SergejJurecko/mio_httpc/files/5984589/mio_httpc-unwrap-panic.tar.gz)

Code used for testing: https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/f206362f2e81521bbefb84007cdd25242f6db590/mio_httpc-smoke-test/src/main.rs

**Comment by SergejJurecko** [comment]
Thank  you fixed in 0.9.4
