### ISSUE TITLE
Fetching some websites is very slow compared to curl

### ISSUE THREAD

**Issue by Shnatsel** [SergejJurecko/mio_httpc#29]
Many websites, e.g. http://globalvision2000.com, take over a minute to download with mio_httpc, while curl completes in just a few seconds.

curl:
```
0.01user 0.01system 0:02.04elapsed 1%CPU (0avgtext+0avgdata 12728maxresident)k
0inputs+0outputs (0major+834minor)pagefaults 0swaps
```

mio_httpc:
```
0.00user 0.02system 1:07.08elapsed 0%CPU (0avgtext+0avgdata 4244maxresident)k
0inputs+0outputs (0major+277minor)pagefaults 0swaps
```

There's at least 70,000 such websites in the top million, although I didn't test the entire million because this issue was making the test unbearably slow. I'm using [Tranco list generated on the 3rd of February](https://tranco-list.eu/list/3G6L).

Archive with all the occurrences I've encountered: [mio_httpc-timeouts.tar.gz](https://github.com/SergejJurecko/mio_httpc/files/5984667/mio_httpc-timeouts.tar.gz)

Exact code used for testing mio_httpc, with `Cargo.lock` and all: https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/f206362f2e81521bbefb84007cdd25242f6db590/mio_httpc-smoke-test/src/main.rs

This issue is distinct from #25 because it still happens in v0.9.3

**Comment by SergejJurecko** [comment]
Thank  you fixed in 0.9.4
