### ISSUE TITLE
Timeout does not appear to work

### ISSUE THREAD

**Issue by Shnatsel** [SergejJurecko/mio_httpc#30]
`.timeout_ms` doesn't appear to work in practice: #29 shows 70,000 websites where mio_httpc exceeded the timeout I've set for it (40 seconds), and the process was killed on a one-minute externally-enforced timeout.

All the details for reproducing the issue can be found in #29.

**Comment by Shnatsel** [comment]
In the past, many clients had this issue on a long chain of redirections because they have erroneously reset the timeout on every request in the redirect chain. This might be part of what's happening here.

**Comment by SergejJurecko** [comment]
Thank  you fixed in 0.9.4
