### ISSUE TITLE
"Chunk was larger than configured CallBuilder::chunked_max_chunk" error on >3% of websites

### ISSUE THREAD

**Issue by Shnatsel** [SergejJurecko/mio_httpc#31]
On some websites, e.g. http://odnoklassniki.ru, mio_httpc fails with the following error: 

> Chunk was larger than configured CallBuilder::chunked_max_chunk. 48669

The exact chunk size given in the error message varies somewhat.

curl works fine for the same websites.

There's at least 32979 such websites in the top million (I'm using [Tranco list generated on the 3rd of February](https://tranco-list.eu/list/3G6L)).

Archive with all occurrences (although I didn't run the test on the entire million): [mio_httpc-chunk-cannot-chuck.tar.gz](https://github.com/SergejJurecko/mio_httpc/files/5984772/mio_httpc-chunk-cannot-chuck.tar.gz)

Code used for testing: https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/f206362f2e81521bbefb84007cdd25242f6db590/mio_httpc-smoke-test/src/main.rs

**Comment by SergejJurecko** [comment]
Thank  you fixed in 0.9.4

**Comment by Shnatsel** [comment]
There's still 13628 websites misbehaving with this error except with even higher chunk sizes in 0.9.4. Why is there a max chunk size in the first place? Is the entire chunk stored in memory?

**Comment by Shnatsel** [comment]
I've filed that as a separate issue #35 to make it easier to track
