### ISSUE TITLE
"Httparse error: too many headers" error on many websites

### ISSUE THREAD

**Issue by Shnatsel** [SergejJurecko/mio_httpc#32]
On some websites, e.g. http://trueleafmarket.com, mio_httpc fails with the following error: 

> Httparse error: too many headers

curl works fine for the same websites. `reqwest` doesn't seem to have this issue either, despite also using the `httparse` crate.

There's at least 7295 such websites in the top million (I'm using [Tranco list generated on the 3rd of February](https://tranco-list.eu/list/3G6L)).

Archive with all occurrences (although I didn't run the test on the entire million): [mio_httpc-too-many-headers.tar.gz](https://github.com/SergejJurecko/mio_httpc/files/5984839/mio_httpc-too-many-headers.tar.gz)

Code used for testing: https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/f206362f2e81521bbefb84007cdd25242f6db590/mio_httpc-smoke-test/src/main.rs

**Comment by SergejJurecko** [comment]
Thank you fixed in 0.9.4

**Comment by Shnatsel** [comment]
Thank you for the quick fixes! Would you like me to re-run the test using 0.9.4?

**Comment by SergejJurecko** [comment]
Please
