### ISSUE TITLE
fails with "Error parsing chunked transfer" on some websites

### ISSUE THREAD

**Issue by Shnatsel** [SergejJurecko/mio_httpc#34]
On some websites, e.g. http://eagle.ca, mio_httpc v0.9.4 fails with the following error: 

> Error parsing chunked transfer

Firefox, curl and ureq work fine.

There's 154 such websites in the top million (I'm using [Tranco list generated on the 3rd of February](https://tranco-list.eu/list/3G6L)).

Archive with all occurrences: [mio_httpc-error-parsing-chunked-transfer.tar.gz](https://github.com/SergejJurecko/mio_httpc/files/6095529/mio_httpc-error-parsing-chunked-transfer.tar.gz)

Code used for testing: https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/8e3285a45e1d657744a2697ced1bd8461031fb86/mio_httpc-smoke-test/src/main.rs

**Comment by SergejJurecko** [comment]
0.9.5 is more permissive now. Technically those websites are not really correct in their response. There should be no spaces in chunk size rows.
