### ISSUE TITLE
fails with "IO error: failed to fill whole buffer" on some websites

### ISSUE THREAD

**Issue by Shnatsel** [SergejJurecko/mio_httpc#36]
On some websites, e.g. http://usmilitaryfsbo.com, mio_httpc v0.9.4 fails with the following error: 

> IO error: failed to fill whole buffer

Firefox, curl and ureq work fine.

There's 22 such websites in the top million (I'm using [Tranco list generated on the 3rd of February](https://tranco-list.eu/list/3G6L)).

Archive with all occurrences: [mio_httpc-0.9.4-buffer-half-empty.tar.gz](https://github.com/SergejJurecko/mio_httpc/files/6095553/mio_httpc-0.9.4-buffer-half-empty.tar.gz)

Code used for testing: https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/8e3285a45e1d657744a2697ced1bd8461031fb86/mio_httpc-smoke-test/src/main.rs

**Comment by SergejJurecko** [comment]
This is actually a badly encoded gzip/deflate response. I have changed the error message to be more clear. Fixed in 0.9.5
