### ISSUE TITLE
Any plans on migrating to MIO 0.8?

### ISSUE THREAD

**Issue by serzhiio** [SergejJurecko/mio_httpc#39]

**Comment by SergejJurecko** [comment]
What mio 0.8?

**Comment by serzhiio** [comment]
Just try 
mio = {git="https://github.com/tokio-rs/mio", features=["os-ext","net"]}

**Comment by SergejJurecko** [comment]
If it is not released it is irrelevant.

**Comment by serzhiio** [comment]
but its a master branch

**Comment by serzhiio** [comment]
In any case, i'm just asking...
I see some breaking changes
