### ISSUE TITLE
Httparse(Version) on simple POST requests

### ISSUE THREAD

**Issue by tolgaparlan** [SergejJurecko/mio_httpc#43]
It seems impossible to make basic post/put requests using this library.

Take this snippet:
```
let mut builder = CallBuilder::post(vec![]);
builder.host("127.0.0.1").port(8000).exec().unwrap();
```

Start a simple local server with `python3 -m http.server` and then run the rust client code. The server error is `code 400, message Bad HTTP/0.9 request type ('POST')` and the mio result is `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Httparse(Version)'`. 

Is there a way to change the mio_httpc's internal http version? As I understand it defaults to http 0.9 which only supports GET requests and is very old.

**Comment by SergejJurecko** [comment]
HTTP/1.1 is hard coded: https://github.com/SergejJurecko/mio_httpc/blob/master/src/call.rs#L181

I do not know what your server does, but I doubt it is valid.

**Comment by tolgaparlan** [comment]
I see. I am not sure what might be going wrong on the server side then but I was having a lot of problems with getting a post client up and running with `mio_httpc` and that is why I went looking for root causes. I believe some examples using call builder post would be very appreciated since they are missing right now
