### ISSUE TITLE
When the server doesn't specify Content-length, mio_httpc returns empty body

### ISSUE THREAD

**Issue by dvtomas** [SergejJurecko/mio_httpc#8]
I'm trying to use mio_httpc to get an infinite MJPEG stream from a Hikvision camera. The camera HTTP server doesn't send the Content-Length header, which kind of makes sense since the stream is infinite. However, mio_httpc streaming example (https://github.com/SergejJurecko/mio_httpc/blob/master/examples/get_streaming.rs) returns an empty body instead of forever returning chunks as expected.

That behavior seems to be incorrect. https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4 says at paragraph 5, that unless a special case, a HTTP body length with no Content-Length header specified gets determined by the server closing the connection at the end of the body.

This simple change has fixed the issue for me: https://github.com/dvtomas/mio_httpc/commit/e1007066cf970851faad0904cc6b6d50fe2fc593 . I can turn it into a PR if wanted, but I'm not sure if the change maybe breaks something else, I only tried it with my use case.

**Comment by SergejJurecko** [comment]
Can you try latest master if it works well?

**Comment by dvtomas** [comment]
Works fine for me. Thanks for the quick fix :)

**Comment by SergejJurecko** [comment]
Thank you for the report. New version published.
