### ISSUE TITLE
panic on Duration-Instant subtract on Windows until 5 minutes after start

### ISSUE THREAD

**Issue by dvtomas** [SergejJurecko/mio_httpc#9]
I don't know about other OSes, but on Windows an `Instant - Duration` subtraction fails if `Duration > time since the Windows have started`.

This subtraction was used here:

https://github.com/SergejJurecko/mio_httpc/blob/739cec6ed68c0011f863b5af66da51885c9a3e53/src/dns_cache.rs#L20

This line has been causing panic when using mio_httpc for the first five minutes after Windows start.

PR for this issue is coming soon. Maybe it would be wise to audit other Instant/Duration uses if there's perhaps another problem like this.

**Comment by SergejJurecko** [comment]
I will check for other uses
